### ISSUE TITLE
Actualizar horarios 2025-1

### ISSUE THREAD

**Issue by joaquinchinobelmar** [AlvinIsCrack/horario-usm#2]
Se subieron los horarios 2025-1. Esta herramienta es perfecta, crees que podrías actualizar los horarios de este semestre?? Muchas graciassss

**Comment by joaquinchinobelmar** [comment]
O podrías hacer un tutorial de como descargar los horarios, y así hacer commits para ahorrar tiempo

**Comment by AlvinIsCrack** [comment]
Tengo pensado actualizar la página en general, ya que existen varios
problemas de visualizacion y otros temas que debo de arreglar, pero sí! La
voy a actualizar en cuanto antes, al menos antes de que sea la toma de
horarios
